### PR TITLE
Travis linter

### PR DESCRIPTION
**Pull request by jbonzo**
This PR solves #30. Inside this PR is the following:

- flake8 config which excludes a lint check on several files/directories

- .travis.yml that is a configuration for Travis CI. Currently the yml installs the dependencies as per requirements.txt as well as flake 8, and runs the lint check which will fail if some code does not meet pep8

~This PR is a Work In Progress I am going to add a batch file so the lint script can be run easily on a Windows machine.~ This is no longer WIP. The batch script has been made into a separate issue #37 which should be a different PR.

Other work related to this PR was the integration of Travis CI with this project and some changes made to how PR's will be done. PR's will not be allowed to merge with master if the Travis build fails, that and 1 review is required. The protection based on Travis CI cannot be activated until this PR is merged otherwise all existing PR's would not be able to merge

### CODE REVIEW

**Comment by jrrickerson** [comment]
Thanks for the PR, I'll review this shortly and get it merged once you feel like it's good to go.  Just let me know if you think it's completely done (based on the WIP label)

**Comment by jrrickerson** [comment]
@jbonzo I think this is ready to be merged, if you can just quickly resolve the couple of conflicts from earlier PRs.

**Review by jrrickerson — CHANGES_REQUESTED** [review]
Looks great, thanks for the work.  Please just resolve conflicts and repush and I'll merge this in.

**Comment by jbonzo** [comment]
Should be good now

**Review by jrrickerson — APPROVED** [review]
Looks good.  Please use a rebase to update your PR next time, so we can minimize merge commit to those directly tied to PR merged, and keep history a little cleaner and easier to look through for future contributors.

**Pull request merged**
