### PR TITLE
ignore more files and update steps

### PR DESCRIPTION
**Pull request by phapdinh**

### CODE REVIEW

**Comment by phapdinh** [comment]
Fixes issue #6

**Comment by jrrickerson** [comment]
Thanks for the PR!  I'll review this soon and get it merged in (we're still working on the automated checks so bear with us)

**Review by jrrickerson — APPROVED** [review]
This all looks good, thanks!

**Comment by jrrickerson** [comment]
Thanks for the PR.  I appreciate you helping debug the Beginner's Guide.  This looks good to go ahead and merge, so sorry for the delay!

**Pull request merged**
